# pnpm-workspace.yaml
packages:
  # all packages in direct subdirectories of packages/
  - "packages/*"
  # all packages in subdirectories of components/
  - "shared/**"
  - "!packages/architectura-test"
